### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by rlleshi** [gambit4348/deception-detection-review-2022#1]
Hi. Thanks a lot for putting this review paper together. 

I was wondering if during your research you got hold of any of the datasets in the domain. It seems like it's rather hard to come by them. The only one I've been able to get a hold of so far is the _Real-life Deception Detection_ dataset from 2016.

If so, would you mind sharing them?

**Comment by gambit4348** [comment]
Hello,

First of all, sorry for taking this long to answer. Indeed, most dataset are kept secret from their makers. As you have already noticed, only the RLTDDD is available for open access. Most articles not even name their datasets and in general they don't mention any way to get them.

I would share everything if I could!

Best regards!

A;ex
